#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  labels:
#    app: nginx
#  name: nginx
#  namespace: default
#spec:
#  replicas: 3
#  selector:
#    matchLabels:
#      app: nginx
#  template:
#    metadata:
#      labels:
#        app: nginx
#    spec:
#      containers:
#      - name: nginx
#        image: nginx
#        ports:
#        - containerPort: 80

---

#apiVersion: v1
#kind: Service
#metadata:
#  name: nginx
#  namespace: default
#spec:
#  selector:
#    app: nginx
#  ports:
#  - port: 80
#    protocol: TCP
#    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-resource
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nginx.home.ringhus.dk
    secretName: letsencrypt-prod
  rules:
  - host: nginx.home.ringhus.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80