apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rancher-demo
spec:
  tls:
    - hosts:
        - rancher-demo.home.ringhus.dk
      secretName: tls-cert
  rules:
  - host: rancher-demo.home.ringhus.dk
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rancher-demo-clusterip
            port:
              number: 80

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-clusterip
spec:
  type: ClusterIP
  ports:
    - name: rancher-demo
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: rancher-demo

---

apiVersion: v1
kind: Service
metadata:
  name: rancher-demo-nodeport
spec:
  type: NodePort
  selector:
    app: rancher-demo
  ports:
    - name: web
      port: 8080
      targetPort: web
      nodePort: 31684
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rancher-demo
  template:
    metadata:
      labels:
        app: rancher-demo
    spec:
      containers:
        - image: bashofmann/rancher-demo:1.1.0
          name: rancher-demo
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: web
              protocol: TCP
          env:
            - name: COW_COLOR
              value: purple
          readinessProbe:
            httpGet:
              port: web
              path: /
