apiVersion: v1
kind: Namespace
metadata:
  name: cluster-issuer-test
---
#apiVersion: cert-manager.io/v1
#kind: Issuer
#metadata:
#  name: test-selfsigned
#  namespace: cert-manager-test
#spec:
#  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: letsencrypt-staging-test
  namespace: cluster-issuer-test
spec:
  dnsNames:
    - ci.home.ringhus.dk
  secretName: cluster-issuer-tls
  issuerRef:
    name: letsencrypt-staging